export const categoriesName = [
  "plants",
  "flowers",
  "vases",
  "pottery",
  "candles",
  "seeds",
] as const;

// data/categories.ts
export const categories = [
  {
    name: "Flowers",
    image: "/bouqet.jpg",
  },
  {
    name: "Vases",
    image: "/vase.jpg",
  },
  {
    name: "Plants",
    image: "/flowers.jpg",
  },
  {
    name: "Pottery",
    image: "/pottery.jpg",
  },
  {
    name: "Candles",
    image: "/candles.jpg",
  },
  {
    name: "Seeds",
    image: "/seeds1.webp",
  },
]


export type Category = typeof categoriesName[number];



export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: Category;
}

export const products: Product[] = [
  // 🌿 PLANTS
  {
    id: "plant-1",
    name: "Monstera Deliciosa",
    description: "A lush indoor plant with large, split leaves.",
    price: 1299,
    image: "/skeleton.webp",
    category: "plants",
  },
  {
    id: "plant-2",
    name: "Snake Plant",
    description: "Low-maintenance plant perfect for modern interiors.",
    price: 799,
    image: "/skeleton.webp",
    category: "plants",
  },
  {
    id: "plant-3",
    name: "Fiddle Leaf Fig",
    description: "Elegant plant with bold, glossy leaves.",
    price: 1899,
    image: "/skeleton.webp",
    category: "plants",
  },
  {
    id: "plant-4",
    name: "Peace Lily",
    description: "Air-purifying plant with soft white blooms.",
    price: 899,
    image: "/skeleton.webp",
    category: "plants",
  },
  {
    id: "plant-5",
    name: "ZZ Plant",
    description: "Hardy plant with waxy green leaves.",
    price: 999,
    image: "/skeleton.webp",
    category: "plants",
  },
  {
    id: "plant-6",
    name: "Areca Palm",
    description: "Brightens rooms with tropical vibes.",
    price: 1599,
    image: "/skeleton.webp",
    category: "plants",
  },
  {
    id: "plant-7",
    name: "Rubber Plant",
    description: "Bold statement plant with deep green leaves.",
    price: 1199,
    image: "/skeleton.webp",
    category: "plants",
  },
  {
    id: "plant-8",
    name: "Aloe Vera",
    description: "Medicinal plant with minimal care needs.",
    price: 499,
    image: "/skeleton.webp",
    category: "plants",
  },
  {
    id: "plant-9",
    name: "Boston Fern",
    description: "Soft foliage ideal for hanging baskets.",
    price: 699,
    image: "/skeleton.webp",
    category: "plants",
  },
  {
    id: "plant-10",
    name: "Calathea Orbifolia",
    description: "Decorative plant with striped leaves.",
    price: 1499,
    image: "/skeleton.webp",
    category: "plants",
  },

  // 🌸 FLOWERS
  {
    id: "flower-1",
    name: "Rose Bouquet",
    description: "Classic red roses wrapped elegantly.",
    price: 999,
    image: "/skeleton.webp",
    category: "flowers",
  },
  {
    id: "flower-2",
    name: "Tulip Mix",
    description: "Bright tulips perfect for any occasion.",
    price: 1099,
    image: "/skeleton.webp",
    category: "flowers",
  },
  {
    id: "flower-3",
    name: "Sunflower Bunch",
    description: "Cheerful sunflowers full of warmth.",
    price: 899,
    image: "/skeleton.webp",
    category: "flowers",
  },
  {
    id: "flower-4",
    name: "Orchid Stem",
    description: "Elegant orchid with long-lasting blooms.",
    price: 1299,
    image: "/skeleton.webp",
    category: "flowers",
  },
  {
    id: "flower-5",
    name: "Lily Arrangement",
    description: "Fragrant lilies arranged with care.",
    price: 1199,
    image: "/skeleton.webp",
    category: "flowers",
  },
  {
    id: "flower-6",
    name: "Peony Bunch",
    description: "Soft, romantic peonies.",
    price: 1499,
    image: "/skeleton.webp",
    category: "flowers",
  },
  {
    id: "flower-7",
    name: "Daisy Basket",
    description: "Fresh daisies in a rustic basket.",
    price: 799,
    image: "/skeleton.webp",
    category: "flowers",
  },
  {
    id: "flower-8",
    name: "Carnation Mix",
    description: "Colorful carnations for daily décor.",
    price: 699,
    image: "/skeleton.webp",
    category: "flowers",
  },
  {
    id: "flower-9",
    name: "Lavender Bunch",
    description: "Calming lavender with natural aroma.",
    price: 899,
    image: "/skeleton.webp",
    category: "flowers",
  },
  {
    id: "flower-10",
    name: "Wildflower Wrap",
    description: "Seasonal wildflowers hand-tied.",
    price: 999,
    image: "/skeleton.webp",
    category: "flowers",
  },

  // 🏺 VASES
  {
    id: "vase-1",
    name: "Ceramic White Vase",
    description: "Minimal ceramic vase for modern homes.",
    price: 699,
    image: "/skeleton.webp",
    category: "vases",
  },
  {
    id: "vase-2",
    name: "Glass Cylinder Vase",
    description: "Clear glass vase for tall stems.",
    price: 599,
    image: "/skeleton.webp",
    category: "vases",
  },
  {
    id: "vase-3",
    name: "Stoneware Vase",
    description: "Handcrafted stoneware finish.",
    price: 899,
    image: "/skeleton.webp",
    category: "vases",
  },
  {
    id: "vase-4",
    name: "Matte Black Vase",
    description: "Bold statement vase with matte finish.",
    price: 999,
    image: "/skeleton.webp",
    category: "vases",
  },
  {
    id: "vase-5",
    name: "Terracotta Vase",
    description: "Earthy tones with rustic charm.",
    price: 649,
    image: "/skeleton.webp",
    category: "vases",
  },
  {
    id: "vase-6",
    name: "Ribbed Glass Vase",
    description: "Textured glass with soft reflections.",
    price: 799,
    image: "/skeleton.webp",
    category: "vases",
  },
  {
    id: "vase-7",
    name: "Tall Minimal Vase",
    description: "Slim vase for modern arrangements.",
    price: 1099,
    image: "/skeleton.webp",
    category: "vases",
  },
  {
    id: "vase-8",
    name: "Rounded Clay Vase",
    description: "Soft rounded shape, handcrafted.",
    price: 899,
    image: "/skeleton.webp",
    category: "vases",
  },
  {
    id: "vase-9",
    name: "Speckled Vase",
    description: "Natural speckled ceramic finish.",
    price: 749,
    image: "/skeleton.webp",
    category: "vases",
  },
  {
    id: "vase-10",
    name: "Minimal Beige Vase",
    description: "Neutral tones for any space.",
    price: 699,
    image: "/skeleton.webp",
    category: "vases",
  },

  // 🕯️ CANDLES
  {
    id: "candle-1",
    name: "Lavender Soy Candle",
    description: "Relaxing lavender scent.",
    price: 399,
    image: "/skeleton.webp",
    category: "candles",
  },
  {
    id: "candle-2",
    name: "Vanilla Bean Candle",
    description: "Warm vanilla aroma.",
    price: 449,
    image: "/skeleton.webp",
    category: "candles",
  },
  {
    id: "candle-3",
    name: "Eucalyptus Candle",
    description: "Fresh, clean eucalyptus notes.",
    price: 499,
    image: "/skeleton.webp",
    category: "candles",
  },
  {
    id: "candle-4",
    name: "Amber Glow Candle",
    description: "Rich amber with woody tones.",
    price: 549,
    image: "/skeleton.webp",
    category: "candles",
  },
  {
    id: "candle-5",
    name: "Rose Scented Candle",
    description: "Soft floral rose fragrance.",
    price: 449,
    image: "/skeleton.webp",
    category: "candles",
  },
  {
    id: "candle-6",
    name: "Sandalwood Candle",
    description: "Earthy and calming scent.",
    price: 599,
    image: "/skeleton.webp",
    category: "candles",
  },
  {
    id: "candle-7",
    name: "Citrus Burst Candle",
    description: "Bright citrus energy.",
    price: 399,
    image: "/skeleton.webp",
    category: "candles",
  },
  {
    id: "candle-8",
    name: "Forest Pine Candle",
    description: "Fresh pine forest aroma.",
    price: 499,
    image: "/skeleton.webp",
    category: "candles",
  },
  {
    id: "candle-9",
    name: "Minimal Wax Candle",
    description: "Unscented minimal candle.",
    price: 299,
    image: "/skeleton.webp",
    category: "candles",
  },
  {
    id: "candle-10",
    name: "Herbal Tea Candle",
    description: "Herbal blend for calm evenings.",
    price: 449,
    image: "/skeleton.webp",
    category: "candles",
  },

  // 🌱 SEEDS
  {
    id: "seed-1",
    name: "Basil Seeds",
    description: "Fresh basil for home gardens.",
    price: 149,
    image: "/skeleton.webp",
    category: "seeds",
  },
  {
    id: "seed-2",
    name: "Sunflower Seeds",
    description: "Grow tall, vibrant sunflowers.",
    price: 199,
    image: "/skeleton.webp",
    category: "seeds",
  },
  {
    id: "seed-3",
    name: "Lavender Seeds",
    description: "Grow fragrant lavender plants.",
    price: 249,
    image: "/skeleton.webp",
    category: "seeds",
  },
  {
    id: "seed-4",
    name: "Mint Seeds",
    description: "Easy-to-grow mint leaves.",
    price: 149,
    image: "/skeleton.webp",
    category: "seeds",
  },
  {
    id: "seed-5",
    name: "Rose Seeds",
    description: "Classic roses for your garden.",
    price: 299,
    image: "/skeleton.webp",
    category: "seeds",
  },
  {
    id: "seed-6",
    name: "Chili Seeds",
    description: "Spicy chilies for home use.",
    price: 129,
    image: "/skeleton.webp",
    category: "seeds",
  },
  {
    id: "seed-7",
    name: "Tomato Seeds",
    description: "Juicy tomatoes at home.",
    price: 149,
    image: "/skeleton.webp",
    category: "seeds",
  },
  {
    id: "seed-8",
    name: "Coriander Seeds",
    description: "Fresh coriander leaves.",
    price: 99,
    image: "/skeleton.webp",
    category: "seeds",
  },
  {
    id: "seed-9",
    name: "Marigold Seeds",
    description: "Bright marigold flowers.",
    price: 179,
    image: "/skeleton.webp",
    category: "seeds",
  },
  {
    id: "seed-10",
    name: "Spinach Seeds",
    description: "Nutritious leafy greens.",
    price: 129,
    image: "/skeleton.webp",
    category: "seeds",
  },
];

export const plants:Product[] = [
  {
    id: "plant-1",
    name: "Monstera Deliciosa",
    description: "Large tropical plant with iconic split leaves.",
    price: 1299,
    image: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b",
    category: "plants",
  },
  {
    id: "plant-2",
    name: "Snake Plant",
    description: "Low-maintenance indoor plant with upright leaves.",
    price: 799,
    image: "https://images.unsplash.com/photo-1615484477778-ca3b77940c25",
    category: "plants",
  },
  {
    id: "plant-3",
    name: "Fiddle Leaf Fig",
    description: "Elegant plant with large glossy leaves.",
    price: 1599,
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb",
    category: "plants",
  },
  {
    id: "plant-4",
    name: "Peace Lily",
    description: "Air-purifying plant with white blooms.",
    price: 699,
    image: "https://images.unsplash.com/photo-1598880940952-7d6fdbb9c66b",
    category: "plants",
  },
  {
    id: "plant-5",
    name: "Aloe Vera",
    description: "Medicinal succulent, easy to care for.",
    price: 499,
    image: "https://images.unsplash.com/photo-1614594895304-fe711e03d66b",
    category: "plants",
  },
  {
    id: "plant-6",
    name: "Rubber Plant",
    description: "Bold foliage plant with thick leaves.",
    price: 1199,
    image: "https://images.unsplash.com/photo-1618220179428-22790b461013",
    category: "plants",
  },
  {
    id: "plant-7",
    name: "Areca Palm",
    description: "Brightens interiors with feathery fronds.",
    price: 999,
    image: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae",
    category: "plants",
  },
  {
    id: "plant-8",
    name: "ZZ Plant",
    description: "Thrives in low light and minimal watering.",
    price: 899,
    image: "https://images.unsplash.com/photo-1615486364462-ef6363adbc18",
    category: "plants",
  },
  {
    id: "plant-9",
    name: "Boston Fern",
    description: "Classic hanging fern with lush greenery.",
    price: 749,
    image: "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20",
    category: "plants",
  },
  {
    id: "plant-10",
    name: "Calathea",
    description: "Decorative plant with patterned leaves.",
    price: 1099,
    image: "https://images.unsplash.com/photo-1593691509543-c55fb32d8de5",
    category: "plants",
  },
];

export const flowers:Product[] = [
  {
    id: "flower-1",
    name: "Rose Bouquet",
    description: "Classic red roses for every occasion.",
    price: 599,
    image: "/red-flowers2.jpg",
    category: "flowers",
  },
  {
    id: "flower-2",
    name: "Tulip Bunch",
    description: "Fresh tulips in vibrant colors.",
    price: 499,
    image: "/red-flowers2.jpg",
    category: "flowers",
  },
  {
    id: "flower-3",
    name: "Sunflower Set",
    description: "Bright sunflowers to lift your mood.",
    price: 399,
    image: "/red-flowers2.jpg",
    category: "flowers",
  },
  {
    id: "flower-4",
    name: "Orchid Pot",
    description: "Elegant orchids with long-lasting blooms.",
    price: 899,
    image: "/red-flowers2.jpg",
    category: "flowers",
  },
  {
    id: "flower-5",
    name: "Daisy Basket",
    description: "Cheerful white daisies in a basket.",
    price: 349,
    image: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6",
    category: "flowers",
  },
  {
    id: "flower-6",
    name: "Lavender Bundle",
    description: "Soothing fragrance and rustic charm.",
    price: 449,
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9",
    category: "flowers",
  },
  {
    id: "flower-7",
    name: "Mixed Floral Vase",
    description: "A vibrant mix of seasonal flowers.",
    price: 699,
    image: "https://images.unsplash.com/photo-1504208434309-cb69f4fe52b0",
    category: "flowers",
  },
  {
    id: "flower-8",
    name: "Peony Arrangement",
    description: "Soft pastel peonies with lush petals.",
    price: 799,
    image: "https://images.unsplash.com/photo-1525310072745-f49212b5ac6d",
    category: "flowers",
  },
  {
    id: "flower-9",
    name: "Lily Bouquet",
    description: "Elegant lilies with a gentle fragrance.",
    price: 549,
    image: "https://images.unsplash.com/photo-1501973801540-537f08ccae7b",
    category: "flowers",
  },
  {
    id: "flower-10",
    name: "Wildflower Mix",
    description: "Natural and colorful wildflower blend.",
    price: 399,
    image: "https://images.unsplash.com/photo-1468327768560-75b778cbb551",
    category: "flowers",
  },
];

export const vases:Product[] = [
  {
    id: "vase-1",
    name: "Ceramic White Vase",
    description: "Minimal matte ceramic vase.",
    price: 699,
    image: "https://images.unsplash.com/photo-1588854337115-1c67d9247e4d",
    category: "vases",
  },
  {
    id: "vase-2",
    name: "Glass Cylinder Vase",
    description: "Transparent vase for modern interiors.",
    price: 499,
    image: "https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd",
    category: "vases",
  },
  {
    id: "vase-3",
    name: "Terracotta Vase",
    description: "Earthy handcrafted clay vase.",
    price: 599,
    image: "https://images.unsplash.com/photo-1616628182506-d0bb4f70e3db",
    category: "vases",
  },
  {
    id: "vase-4",
    name: "Black Stoneware Vase",
    description: "Premium stoneware with matte finish.",
    price: 899,
    image: "https://images.unsplash.com/photo-1616627451359-7d9c3b2a0f5d",
    category: "vases",
  },
  {
    id: "vase-5",
    name: "Ribbed Ceramic Vase",
    description: "Textured ceramic vase for decor.",
    price: 749,
    image: "https://images.unsplash.com/photo-1616627561839-0f58b3d1e6c1",
    category: "vases",
  },
];

export const candles:Product[] = [
  {
    id: "candle-1",
    name: "Soy Wax Candle",
    description: "Eco-friendly candle with soft aroma.",
    price: 399,
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108",
    category: "candles",
  },
  {
    id: "candle-2",
    name: "Lavender Candle",
    description: "Relaxing lavender fragrance.",
    price: 449,
    image: "https://images.unsplash.com/photo-1616627451836-ec7c3c3b9e3d",
    category: "candles",
  },
  {
    id: "candle-3",
    name: "Vanilla Scented Candle",
    description: "Warm vanilla notes.",
    price: 349,
    image: "https://images.unsplash.com/photo-1607082349566-187342175e2f",
    category: "candles",
  },
  {
    id: "candle-4",
    name: "Minimal Jar Candle",
    description: "Modern jar candle for decor.",
    price: 499,
    image: "https://images.unsplash.com/photo-1616628182304-6b53d1c4f3df",
    category: "candles",
  },
];

export const seeds:Product[] = [
  {
    id: "seed-1",
    name: "Basil Seeds",
    description: "Fresh basil for home gardens.",
    price: 199,
    image: "https://images.unsplash.com/photo-1615484478209-5c2b6c8e3f1f",
    category: "seeds",
  },
  {
    id: "seed-2",
    name: "Sunflower Seeds",
    description: "Grow tall sunflowers easily.",
    price: 149,
    image: "https://images.unsplash.com/photo-1592921870789-04563d55041c",
    category: "seeds",
  },
  {
    id: "seed-3",
    name: "Tomato Seeds",
    description: "Organic seeds for juicy tomatoes.",
    price: 179,
    image: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10",
    category: "seeds",
  },
];

